# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default='eu-west-1', max_length=16),
        ),
    ]
