# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160716_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='console_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
