# Generated by Django 2.0.1 on 2018-01-23 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20160805_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
