# Generated by Django 2.2.28 on 2022-07-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auditentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='collect date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer')),
            ],
            options={
                'ordering': ['customer', 'date'],
            },
        ),
    ]
